baseurl: ""
url: "https://amirmahdi-chiti.github.io"
title: Amirmahdi Chiti
theme: coder
languagecode: en-us
defaultcontentlanguage: en-us
paginate: 20
#disqusShortname: yourdiscussshortname
markup:
  highlight:
    style: github-dark
params:
  cover:
   linkFullImages: true
  author: Amirmahdi Chiti
  info: 
    - DevOps Engineer
    - Computer Student
  description: Amirmahdi Chiti's personal website
  keywords: 'blog,developer,personal,devops'
  avatarurl: images/avatar.jpg
  faviconSVG: images/favicon.svg
  favicon_32: images/favicon-32x32.png
  favicon_16: images/favicon-16x16.png
  since: 2019
  enableTwemoji: true
  colorScheme: auto
  hidecolorschemetoggle: false
  social:
    - name: Github
      icon: fa fa-github fa-2x
      weight: 1
      url: 'https://github.com/Amirmahdi-Ch'
    - name: Gitlab
      icon: fa fa-gitlab fa-2x
      weight: 2
      url: 'https://gitlab.com/Amirmahdi.Ch'
    - name: LinkedIn
      icon: fa fa-linkedin fa-2x
      weight: 4
      url: 'https://www.linkedin.com/in/amirmahdi-chiti'
    - name: Email
      icon: fa fa-envelope fa-2x
      weight: 5
      url: 'mailto'
    - name: Telegram
      icon: fa fa-telegram fa-2x
      weight: 6
      url: 'https://telegram.me/amirmahdichiti'
taxonomies:
  category: categories
  series: series
  tag: tags
  author: authors
menu:
  main:
    - name: Blog
      weight: 1
      url: 'posts/first/'
    - name: About
      weight: 2
      url: 'about/'
